title: FedishareNX
description: Web API that converts Nintendo Switch Twitter API requests to ActivityPub (Mastodon).
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
